#!/bin/sh

xrdb -load ~/.config/sx/xresources
xrandr --newmode "1920x1080R"  138.50  1920 1968 2000 2080  1080 1083 1088 1111 +HSync -VSync && xrandr --addmode DisplayPort-9 1920x1080R && xrandr --output DisplayPort-9 --mode 1920x1080 &
picom &
# feh --no-fehbg --bg-center /usr/share/backgrounds/dusktown.png &
unclutter &
slstatus &
exec dwm
